### ISSUE TITLE
Version support 

### ISSUE THREAD

**Issue by MGlolenstine** [Mubelotix/minecraft-protocol#2]
What versions are supported?
I tested it using [`paper`](https://papermc.io) Minecraft server versions 1.17 and 1.16, but neither could connect without a problem.

What can I do to support newer versions?

**Comment by MGlolenstine** [comment]
I have noticed `VERSION` variable in the `build.rs`, so I'm guessing we can just set it to any version we'd like.

**Comment by Mubelotix** [comment]
This crate was made to support the version 1.16 of the protocol. Many things need to be updated in order to support 1.17 as many packets have seen their structure and behavior modified. This is not something I am going to work on in the near future so you will have to be patient

**Comment by MGlolenstine** [comment]
That's all good. I wasn't complaining, just pointing out that I haven't seen the version mentioned anywhere.
I was also up for helping out with support for newer versions.
